name: ring_mobile
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  firebase_crashlytics: ^0.2.0    # main
  firebase_messaging: ^7.0.0       # main
  provider: ^4.3.2+2                  # main
  cached_network_image: ^2.3.2+1 # common
  dio: ^3.0.10                       # common
  connectivity: ^0.4.9+3
  flutter_svg: ^0.19.0              # common
  url_launcher: ^5.5.0              # common
  shared_preferences: ^0.5.12      # app_preferences
  floor: ^0.14.0                     # dio For local Database
  flutter_slidable: ^0.5.7          # swipable list item
  image_picker: ^0.6.7+11            # image picker
  permission_handler: ^5.0.1+1      # permissions
  liquid_swipe: ^1.5.0              # splash_intro_screen liquir swipe for splash intro screen
  pin_code_text_field: ^1.7.1       # verify_email_screen
  
  encrypt: ^4.0.3                   # security
  dotted_border: ^1.0.6             # invite friends screen
  flutter_rating_bar: ^3.0.1+1
  flutter_country_picker: ^0.1.6    # country picker
  smooth_page_indicator: ^0.2.0     # page indicator
  geolocation: ^1.1.2               # location
  geocoder: ^0.2.1
  flutter_image_compress: ^0.7.0
  flutter_staggered_grid_view: ^0.3.2
  align_positioned: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/locale/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
